apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: greeting-app-build-push
spec:
  workspaces:
    - name: sbt-repo
  resources:
    inputs:
      - name: greeting-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: echo
      image: busybox
      script: |
        #!/bin/sh
        set -xe
        echo hello!  $(workspaces.sbt-repo.path)
        pwd 
        ls -l 
    - name: dist
      image: hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.10_2.13.2
      workingDir: /workspace/greeting-source
      script: |
        #!/bin/sh
        set -xe
        mkdir -p $(workspaces.sbt-repo.path)/.ivy2 
        mkdir -p $(workspaces.sbt-repo.path)/.cache
        mkdir -p $(workspaces.sbt-repo.path)/.sbt
        mkdir -p $(workspaces.sbt-repo.path)/.coursier
        sbt \
        -Dsbt.ivy.home=$(workspaces.sbt-repo.path)/.ivy2 \
        -Divy.home=.$(workspaces.sbt-repo.path)/.ivy2 \
        -Dsbt.global.base=$(workspaces.sbt-repo.path)/.sbt  \
        -Dcoursier.cache=$(workspaces.sbt-repo.path)/.cache \
        -Dsbt.coursier.home=$(workspaces.sbt-repo.path)/.coursier \
        dist  
    - name : unzip
      image : busybox
      workingDir: /workspace/greeting-source/target/universal
      script: |
        #!/bin/sh
        set -xe
        mkdir -p app 
        unzip -q -d  app play-scala-macwire-di-example-2.8.x.zip 
    - name: build
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      workingDir: /workspace/greeting-source/target/universal/app
      script: |
        #!/bin/sh
        set -xe
        ls -l  
        buildah version
        container=$(buildah from adoptopenjdk:11-jre-openj9)
        buildah run  $container -- mkdir -p /opt/app
        buildah copy $container play-scala-macwire-di-example-2.8.x /opt/app/play-scala-macwire-di-example-2.8.x
        buildah config --workingdir /opt/app/play-scala-macwire-di-example-2.8.x $container
        buildah config --label maintainer="Kiran Kumar <gmkumar2005@gmail.com>" $container
        buildah config --entrypoint "bin/play-scala-macwire-di-example \
        -Dplay.http.secret.key=ad31779d4ee49d5ad5162bf1429c32e2e9933f3b" $container
        buildah commit --format docker $container registry.192.168.23.31.nip.io/play-demo/greeting:latest
        buildah push --tls-verify=false registry.192.168.23.31.nip.io/play-demo/greeting:latest
     