apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: play-demo-pipeline
spec:
  workspaces:
    - name: local-sbt-repo
  resources:
    - name: play-demo-source
      type: git
    - name: play-demo-builtImage
      type: image
  tasks:
    - name: build-push-app
      workspaces:
        - name: sbt-repo
          workspace: local-sbt-repo
      taskRef:
        name: greeting-app-build-push
      resources:
        inputs:
          - name: greeting-source
            resource: play-demo-source
        outputs:
          - name: builtImage
            resource: play-demo-builtImage
    - name: deploy-app
      workspaces:
        - name: sbt-repo
          workspace: local-sbt-repo
      params:
        - name: path
          value: $(resources.inputs.app-source.path)/tektoncd/manifest/greeting-app-deployment.yaml
        - name: yamlPathToImage
          value: $(resources.inputs.image.url) 
        - name: namespace
          value: play-demo
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - build-push-app
      resources:
        inputs:
          - name: app-source
            resource: play-demo-source
          - name: image
            resource: play-demo-builtImage
        