apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: play-demo-pipeline
spec:
  results:
    - name: image-with-digest
      description: Full path of out image with digest
      value: $(tasks.build-push-app.results.builtImage-digest)
  workspaces:
    - name: local-sbt-repo
  resources:
    - name: play-demo-source
      type: git
    - name: play-demo-builtImage
      type: image
  tasks:
    - name: build-push-app
      workspaces:
        - name: sbt-repo
          workspace: local-sbt-repo
      taskRef:
        name: greeting-app-build-push
      resources:
        inputs:
          - name: greeting-source
            resource: play-demo-source
        outputs:
          - name: builtImage
            resource: play-demo-builtImage
    - name: deploy-app
      workspaces:
        - name: sbt-repo
          workspace: local-sbt-repo
      params:
        - name: path
          value: $(resources.inputs.greeting-source.path)/tektoncd/manifest/greeting-app-deployment.yaml
        - name: namespace
          value: play-demo
        - name: image-url-with-digest
          value: $(tasks.build-push-app.results.builtImage-digest)
        - name: registry-host
          value: localhost:32000/play-demo/greeting-app
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - build-push-app
      resources:
        inputs:
          - name: greeting-source
            resource: play-demo-source